name: Regrassion suite

on:

push:
  branches:
    -master
  pull_request:
    branches:
      -master
jobs:
  run-tests:
    run_on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirments.txt

      - name: Run test
        run: |
          pytest -s --html=reports.html 

      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: pytest-report
          
